# Generated by Django 3.1.5 on 2021-01-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bd',
            new_name='Bb',
        ),
    ]
